steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker build --build-arg "STORYBOOK_BASE_URL=$_BASE_URL" -t $_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:latest -f .docker/Dockerfile .'
    id: Build
  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:latest'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: Deploy
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:latest'
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:latest'
options:
  substitutionOption: ALLOW_LOOSE
